repos:
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.8

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.1.1
#   hooks:
#   - id: mypy

# - repo: local
#   hooks:
#   - id: pylint
#     name: pylint
#     entry: pylint
#     language: system
#     types: [python]
#     require_serial: true
#     args:
#     - --output-format=colorized
#     - --reports=no

# -   repo: local
#     hooks:
#     -   id: re-run-training
#         name: Re-run the training script
#         entry: ./cohorts/2023/02-experiment-tracking/homework/re_run_training.sh
#         language: script
#         pass_filenames: false
